/*!	\file hikstream.h
 *	\brief Header file containing functions for streaming HumanIK characterizations.
 */

/**************************************************************************************

Copyright © 2009 Autodesk, Inc.
All Rights Reserved.

The coded instructions, statements, computer programs, and/or related material (collectively "Data")
in these files contain unpublished information proprietary to Autodesk, Inc., ("Autodesk") which is
protected by Canada and United States of America federal copyright law and by international treaties.

The Data may not be disclosed or distributed to third parties, in whole or in part, without the prior
written consent of Autodesk.

THE DATA IS PROVIDED "AS IS" AND WITHOUT WARRANTY. ALL WARRANTIES ARE EXPRESSLY EXCLUDED AND DISCLAIMED.
AUTODESK MAKES NO WARRANTY OF ANY KIND WITH RESPECT TO THE DATA, EXPRESS, IMPLIED OR ARISING BY CUSTOM
OR TRADE USAGE, AND DISCLAIMS ANY IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR
FITNESS FOR A PARTICULAR PURPOSE OR USE. WITHOUT LIMITING THE FOREGOING, AUTODESK DOES NOT WARRANT THAT
THE OPERATION OF THE DATA WILL BE UNINTERRUPTED OR ERROR FREE.

IN NO EVENT SHALL AUTODESK, ITS AFFILIATES, PARENT COMPANIES, LICENSORS OR SUPPLIERS ("AUTODESK GROUP")
BE LIABLE FOR ANY LOSSES, DAMAGES OR EXPENSES OF ANY KIND (INCLUDING WITHOUT LIMITATION PUNITIVE OR
MULTIPLE DAMAGES OR OTHER SPECIAL, DIRECT, INDIRECT, EXEMPLARY, INCIDENTAL, LOSS OF PROFITS, REVENUE
OR DATA, COST OF COVER OR CONSEQUENTIAL LOSSES OR DAMAGES OF ANY KIND), HOWEVER CAUSED, AND REGARDLESS
OF THE THEORY OF LIABILITY, WHETHER DERIVED FROM CONTRACT, TORT (INCLUDING, BUT NOT LIMITED TO,
NEGLIGENCE), OR OTHERWISE, ARISING OUT OF OR RELATING TO THE DATA OR ITS USE OR ANY OTHER PERFORMANCE,
WHETHER OR NOT AUTODESK HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS OR DAMAGE.

**************************************************************************************/

#ifndef _HIK_STREAM_
#define _HIK_STREAM_

#include "humanik.h"

#ifdef __cplusplus
extern "C" {
#endif


/** \defgroup stream Streaming Objects To and From Memory
	This section describes the functions provided for reading HumanIK objects from memory streams, and writing HumanIK objects to
	memory buffers.
	\ingroup Object
*/

/**	\brief Creates a new HIKCharacterDefinition and HIKCharacter from the specified binary stream. 
 *
 *	This function is typically used to create a fully characterized HIKCharacter from the contents of a binary file created by the 
 *	Characterization Tool. It can also be used to create a character from the binary stream generated by HIKWriteToStream().
 *	\ingroup stream 
 *	\param[out]	pCharacterDefinition	An HIKCharacterDefinition that reflects which Nodes in the HIKCharacter are used, and which Nodes have DoF and parent offsets.
 *	\param		pStream					A byte stream that contains all the information required by HumanIK to create the HIKCharacterDefinition and HIKCharacter.
 *	\param		pStreamSize				The size of \c pStream, in bytes.
 *	\param		pMalloc					Pointer to a memory allocation function. If you do not have a custom memory allocation function, use &malloc.
 *  \param		pFree					Pointer to a memory de-allocation function. If you do not have a custom memory de-allocation function, use &free.
 *	\param		pValidationString		The customer identification string given to you by Autodesk to license the use of HumanIK in your project.
 *	\param		pValidationKey			The license key given to you by Autodesk to license the use of HumanIK in your project.
 */
HIK_EXPORT HIKCharacter* HIK_API HIKReadFromStream(
    HIKCharacterDefinition* pCharacterDefinition,
    const char* pStream,
    size_t pStreamSize,
    HIKMalloc pMalloc,
    HIKFree pFree,
    const char* pValidationString, 
    unsigned int pValidationKey
    );

/**	\brief Writes the specified HIKCharacterDefinition and HIKCharacter to a byte stream.
 *
 *	You can re-create your HIKCharacterDefinition and HIKCharacter from the contents of this byte stream by calling HIKReadFromStream().
 *  \ingroup stream 
 *  \param		pStreamSize             The size of the byte stream in which the data will be written, in bytes.
 *  \param		pCharacterDefinition	The HIKCharacterDefinition that specifies which Nodes your HIKCharacter uses, and which Nodes have DoF and parent offsets.
 *	\param		pCharacter              The HIKCharacter to be written to the stream.
 *  \param		pBigEndian              Specifies whether or not the stream uses big-endian byte order. Use \c true for big-endian platforms, and \c false for little-endian platforms.
 *	\param		pMalloc					Pointer to a memory allocation function. If you do not have a custom memory allocation function, use &malloc.
 *  \param		pFree					Pointer to a memory de-allocation function. If you do not have a custom memory de-allocation function, use &free.
 *	\param		pValidationString		The customer identification string given to you by Autodesk to license the use of HumanIK in your project.
 *	\param		pValidationKey			The license key given to you by Autodesk to license the use of HumanIK in your project.
 */
HIK_EXPORT char* HIK_API HIKWriteToStream(
    size_t* pStreamSize,
    const HIKCharacterDefinition* pCharacterDefinition,
    const HIKCharacter* pCharacter,
    bool pBigEndian,
    HIKMalloc pMalloc,
    HIKFree pFree,
    const char* pValidationString, 
    unsigned int pValidationKey
    );


#ifdef __cplusplus
}
#endif

#endif
